### PR TITLE
Fix Windows ifdef checks before build; fix field size of AVCodecContext::bit_rate

### PR DESCRIPTION
**Pull request by AndiDog**

### CODE REVIEW

**Comment by AndiDog** [comment]
Added another commit which fixes AVPacket::duration which was changed to 64 bits end of September. Since no feature definition FF_API_xxx was added in that case (see https://github.com/FFmpeg/FFmpeg/commit/b01891a9f08b9d271d75d179b3138242a958ee04), I'm using another definition as distinction between old (c_int) and new (int64_t).

**Comment by meh** [comment]
Oh shit I was sure I had merged this, sorry for the delay.

**Comment by meh** [comment]
This change has broken `AVCodecContext`, can you confirm or deny the `bit_rate` is actually an `int64_t` now?

Because I still see in an `int` in the headers.

**Comment by meh** [comment]
Actually same for duration, the `2.8` branch doesn't have those different types, I think you were looking at `3.0`.

**Comment by meh** [comment]
Yeah I confirm that, those types changed from `2.8` to `3.0`.

**Comment by AndiDog** [comment]
Not sure which FFmpeg version I have on Windows. On Mac OS X, it's ffmpeg-2.8.5 and there's some mismatch. Since I have a real problem related to this (working for me on Windows, not on OS X), I will definitely check.

**Comment by meh** [comment]
@AndiDog I verified myself, what you were using on Windows was either the `master` branch for ffmpeg or the `release/3.0` branch.

I'm gonna work on the updates for `3.0` when it gets packaged for Arch, for now I reverted those type changes.

**Comment by AndiDog** [comment]
I'm working on comparing struct field offsets/sizes at build time so that mismatches between C and Rust will lead to errors. Coming soon - must first test it on more platforms and check more structs.

**Comment by meh** [comment]
@AndiDog that's a really good idea, looking forward to it.

**Comment by AndiDog** [comment]
`bit_rate` is 64-bit from this commit on: https://github.com/FFmpeg/FFmpeg/commit/7404f3bdb90e6a5dcb59bc0a091e2c5c038e557d

Can you check exactly at which commit you currently are? Note also that libav still has `int bit_rate`. I'd like to distinguish by `LIBAVCODEC_VERSION_*` --> for example `cfg!(avcodecVersionMajor > 57 || (avcodecVersionMajor == 57 && avcodecVersionMinor >= 2))`. Not sure if we ever have to distinguish ffmpeg vs. libav – I hope not.

**Comment by meh** [comment]
@AndiDog check the `release/2.8` branch, that's where we're at with `ffmpeg-sys`.

Now that `3.0` is out on Arch I'll be able to do the changes for that.

**Comment by meh** [comment]
Also about libav/ffmpeg, I only plan to support ffmpeg.

**Comment by AndiDog** [comment]
> Also about libav/ffmpeg, I only plan to support ffmpeg.

Very good!

I'd like to support basically any not-too-old FFmpeg version using Cargo features. Hopefully it's easy to implement for `int bit_rate` vs `int64_t bit_rate`. Will keep you updated.

**Pull request merged**
