### PR TITLE
Autogenerated bindings with bindgen.

### PR DESCRIPTION
**Pull request by retrry**
Hello, 
I've spent couple days trying to update to ffmpeg 3.3 and moved binding generation to bindgen from initial implementation. I have updated rust-ffmpeg bindings too, which will be in separate pull request. I know that I still haven't finished interrupt callback support, but it my projects started crashing and I suspected some mismatches due to different ffmpeg versions.

I've tried to use as much as possible from autogenerated bindings, where it wasn't possible I left old implementations.

As you can see I've deleted a lot of stuff from build.rs. I didn't know how to port a lot of that stuff with features to implementation. This is tested on Linux with ffmpeg already available. I didn't want to generate bindings from cloned repo, as I think, that would make build not deterministic.

What are your thoughts on this direction for rust-ffmpeg-sys bindings? What would be needed to move forward with this code?

### CODE REVIEW

**Comment by meh** [comment]
The main issue with this and the lack of features is that the high level wrapper **must** know about what is enabled and disabled, structs change shape with and without some features, enums have more or less variants depending on features, some functions exist or not depending on features.

Then you get the issue with the fact that the ffmpeg installed on the system may have been configured differently from the one from git, which means you always need to run bindgen on the system ffmpeg, unless you're doing a static and explicit build where you can just use the git one and build it.

If a way can be figured out to use bindgen for this I'd be up for it, but I honestly don't know how feasible it actually is, ffmpeg is awful in this regard.

**Comment by retrry** [comment]
I think we could use macro definitions for features.
Let say I don't want FF_API_OLD_OPEN_CALLBACKS feature.
I would add ``.clang_arg("-DFF_API_OLD_OPEN_CALLBACKS=0")`` to bindgen builder and bindgen won't generate those code blocks.

**Comment by meh** [comment]
The issue is they have to be bubbled up upstream to the high level wrapper so the `build.rs` from it can defined the features.

And it's not about wanting or not wanting one feature, it's about giving access to the feature list to crates using this one.

**Comment by retrry** [comment]
So I'm just checking to be sure how to proceed here. These steps would be needed to move forward with this pull request:
1. I need to bring back check_features functionality, that existed.
2. If using ffmpeg from system, bindgen should run against includes from system ffmpeg and I would need to check_features on it.
3. If system ffmpeg is not available build.rs should compile its own ffmpeg and check features against it. Bindgen would run on processed includes(? or I would convert disable/enable features to clang_args so bindgen wouldn't add unavailable features to generated bindings). 
4. Bring back removed feature flags in rust-ffmpeg high level bindings.

Is my understanding correct?

**Comment by meh** [comment]
@retrry yep, that's exactly it.

**Comment by retrry** [comment]
So, I've brought back all code written by you to build.rs. I've modified bindgen to run either against system ffmpeg or processed includes.

I did some testing and my project compiles and runs successfully.

**Comment by retrry** [comment]
I've brought back all removed feature flags for rust-ffmpeg in https://github.com/meh/rust-ffmpeg/pull/81

**Comment by meh** [comment]
Looks good, just a couple nitpicks on meh/rust-ffmpeg#81 and both should be good to merge.

Really nice work 🐼

**Pull request merged**
