### PR TITLE
Support macos

### PR DESCRIPTION
**Pull request by trlim**
This PR enables building for macos and some additional features which will be also helpful for other targets.

* uses `gcc` crate to detect proper compiler for a target
* uses `pkg-config` by default to find preinstalled ffmpeg library when you are not building from source.
  This helps to detect brew installed library on macos.
* By setting `FFMPEG_DIR` environment variable, user can bypass `pkg-config` and override library path.
* User can also select dynamic vs static linking with `static` feature flag.
* But if you force building from source code, none of above applies except detecting `gcc` and works as before.

I also tried to make travis pass on macos but it still fails at `cargo test` step because there is an issue in current implementation of tests.

### CODE REVIEW

**Comment by trlim** [comment]
Further testing showed that static linking with `homebrew` libraries still have an issue which seems not easy to solve immediately.
So dynamic linking with homebrew/custom libraries or building from source are possible options on macos.

**Comment by meh** [comment]
Is the whole `Library` shim thing required? I really don't like it :(

**Comment by trlim** [comment]
Actually I was going to use other values for more features but no need for them now.
I will remove it.

**Comment by trlim** [comment]
Updated with additional trivial changes.

**Comment by meh** [comment]
Looks good, is it ready for merge or do you need to change anything else?

**Comment by trlim** [comment]
It's good for merge.

**Comment by trlim** [comment]
Actually now I have one more change to fix currently broken test.
It can be added here if you are OK or I will create a separate PR for that later.

**Comment by meh** [comment]
Go ahead, add it here :)

**Comment by trlim** [comment]
The test is failing because header file used by C program(which is compiled by test) is different from the files the crate built with.
This commit handles the issue by generating `tmp/.build` text file which contains detected compiler command, options and include paths of ffmpeg headers. Then test module reads the file and can compile the C code with proper options.

**Comment by meh** [comment]
Merged, thanks!

**Pull request closed without merging**
