### PR TITLE
Stop tracking bindgen git as new version was released with needed changes

### PR DESCRIPTION
**Pull request by retrry**
Title explains itself. Sorry for PR noise, but you happened to merge my PR couple minutes before this :)

### CODE REVIEW

**Comment by meh** [comment]
Haha, it's fine, thanks!

**Comment by meh** [comment]
Mmh, I'm getting a failure while building, but it's failing in a useless way:

```
TranslationUnit::parse failed
```

But my backtraces are broken so that's all I get, sounds like a bindgen issue?

**Comment by retrry** [comment]
What Clang version are you using?

**Comment by meh** [comment]
Clang 5.0.

**Comment by retrry** [comment]
Do you have ability to drop down to 4.0? As I see that bindgen isn't being tested on clang 5.0 (https://github.com/servo/rust-bindgen/blob/master/.travis.yml#L19)

**Comment by meh** [comment]
It seems to be happening both on 3.9 and 4.0 too.

**Comment by retrry** [comment]
I have no idea. It is bindgen issue, but I don't know why it doesn't work. I just tried nightly, stable - it worked. I'm on Linux, maybe that? I didn't test it on macOS.

**Comment by meh** [comment]
Linux here too, tried on Arch and Exherbo, even with a backtrace it's useless since it's pointing at line 860 where the bindgen builder is created.

**Comment by retrry** [comment]
And you are using system ffmpeg? Could you try to remove clang_args line, it could pass duplicated include flags or something. I think I'll have to install ArchLinux to test it and see for myself, as otherwise I have no idea.

**Comment by meh** [comment]
Same thing without `clang_args`.

**Comment by retrry** [comment]
Okay, I'll have to install Arch to see it for myself :(

**Pull request merged**
