### PR TITLE
Do not represent C enums by Rust enums

### PR DESCRIPTION
**Pull request by stephaneyfx**
This is more conservative and safer as C enum values do not have to be equal to
one of the enumerators whereas in Rust they do.

### CODE REVIEW

**Comment by barzamin** [comment]
as much as i like this, i think it'll break https://github.com/meh/rust-ffmpeg. i would be open to merging this as _some point_, just not now while we're trying to bring that crate back up to date

**Comment by stephaneyfx** [comment]
Thank you for reviewing. If it helps, I can take a look at the ffmpeg crate and attempt to fix any breakage this change would cause.

**Comment by barzamin** [comment]
sure! you might want to work on top of one of the ffmpeg 4.0 patches

**Comment by stephaneyfx** [comment]
Sorry, I'm not sure what I should look at. Should I work on top of the master branch of the ffmpeg crate or did you mean I should work on the ffmpeg-next crate?

**Comment by barzamin** [comment]
a branch like this, probably: https://github.com/meh/rust-ffmpeg/pull/115

**Comment by stephaneyfx** [comment]
Thank you!

**Comment by kornelski** [comment]
I see a couple of problems with the change:

* Non-Rust enums are painful in rustdoc documentation. The type becomes an int alias, and you don't see which options are valid.

* Changing them is a semver break. Changing all of them would create a lot of churn.


So I think it'd be better to change them on case-by-case basis if they're really incompatible (e.g. when they're supposed to be bitflags).

**Pull request closed without merging**
