### PR TITLE
build fixes

### PR DESCRIPTION
**Pull request by ereichert**
We fixed a few problems with the build script and added support for linking to a few more libs.

### CODE REVIEW

**Comment by meh** [comment]
Are those new linked libraries needed for ffmpeg to build?

**Comment by ereichert** [comment]
On Linux they are.

**Comment by ereichert** [comment]
I think some of them are required on OS X as well but we've abandoned OS X for our dev work when it comes to FFMPEG so I'm not 100% certain.

**Comment by ereichert** [comment]
One more:  We only tested it on CentOS 6.x.

**Comment by meh** [comment]
What I'm mostly concerned about is the fact they're free standing options. If they're _required_ to link properly they should be a default.

**Comment by ereichert** [comment]
Ah.  I'm pretty sure they are required for a relatively default ffmpeg build.  That is, if one doesn't disable some features they are required.

**Comment by meh** [comment]
I know this could be hard to figure out, but if you could find what current Cargo features require the linkage for that and add them as feature dependencies it would be nice.

Otherwise the best option is probably to just add them as dependencies to `build` itself.

**Comment by ereichert** [comment]
@ryandbair is close to having something working.  We'll send a PR as soon as we review it and work it through our fork.

**Comment by ereichert** [comment]
@meh Check it out now.

**Comment by meh** [comment]
Looks good, could you squash the commits please?

Otherwise I'll do it myself :panda_face:

**Comment by ereichert** [comment]
I'll squash them this morning.

**Comment by ereichert** [comment]
Squashed as much as possible without blowing up an entire day. :)

**Comment by meh** [comment]
Kind of merged by hand.

**Pull request closed without merging**
