### PR TITLE
Upgrade deps

### PR DESCRIPTION
**Pull request by kornelski**

### CODE REVIEW

**Comment by meh** [comment]
Aside from bindgen, isn't every other update useless given the version filter specified includes the changes already?

**Comment by kornelski** [comment]
Less-than-latest versions of dependencies aren't getting tested. There's no guarantee that the lowest matching versions actually work, e.g. if you specify `= "1.0"`, but accidentally depend on a feature added in `1.1`, it would break if Cargo ever selected the actual lower version (due to someone's lockfile, pinned versions, `-Z minimal-versions` flag). It's safest to bump versions to actually latest.

**Comment by meh** [comment]
Makes sense, thanks!

**Comment by meh** [comment]
Makes sense, thanks!

**Pull request merged**
